import { type VNLang } from './types';

// 播放器內 UI 文案：跟隨 VN 自身的 JP/中 切換（非 dashboard i18n）。

const ja = {
  pageTitle: '面接シアター',
  pageSub: 'ビジュアルノベル式・PM模擬面接。観るだけで「面接の型」が入る練習教材。',
  sampleTag: 'サンプル台本',
  pickTitle: '台本を選ぶ',
  random: 'おまかせで1本 ▶',
  play: '再生 ▶',
  acts: '幕',
  lines: '句',
  startHint: '画面タップ / スペースキーで進む',
  act: '第{n}幕',
  chapters: '章から選ぶ',
  chaptersTitle: '章を選んで再生',
  kaisetsu: '解説',
  auto: 'オート',
  autoFast: '倍速',
  prev: '← 前へ',
  restart: '最初から',
  exit: '終了',
  me: '私',
  innerName: '心の声',
  noteTitle: 'なぜこの回答が良いのか',
  nextHint: '▼ 次へ',
  nextAnswer: '回答へ ▶',
  nextReport: '結果を見る ▶',
  shadowHint: '🎤 まず自分の答えを声に出してから進もう',
  menu: 'メニュー',
  voice: '音声',
  packSection: '各社面接パック',
  staticSection: '台本',
  packBuilding: '音声を生成中…（初回のみ・1分ほど）',
  packAudioNone: '音声未生成',
  packAudioPartial: '音声 一部生成済み',
  packLoadFailed: '台本の読み込みに失敗しました',
  archive: 'アーカイブ',
  archivedSection: 'アーカイブ済み',
  restore: '戻す',
  favorLabel: '面接官',
  reportTitle: '面接評価レポート',
  reportBy: '評価者',
  finalFavor: '最終評価',
  overall: '総評',
  replay: 'もう一度見る',
  backToTitle: '台本選択へ戻る',
  close: '閉じる',
  reviewMode: '復習モード',
  reviewTitle: '面接シアター 総復習',
  reviewSub: '全台本を一括表示。スクロールで一気に見返せます。',
  reviewToc: '目次',
  reviewSearch: '検索',
  reviewBookmarked: 'お気に入り',
  reviewShowInner: '心の声',
  reviewModeFull: '全文',
  reviewModeMine: '自分の回答のみ',
  reviewKpiViews: '閲覧回数',
  reviewKpiToday: '今日の復習時間',
  reviewPickTitle: '復習する台本を選ぶ',
};

const zh: typeof ja = {
  pageTitle: '面試劇場',
  pageSub: '視覺小說式 PM 模擬面試。用「看劇」的方式把面試的型打進身體。',
  sampleTag: '佔位腳本',
  pickTitle: '選擇腳本',
  random: '隨機來一場 ▶',
  play: '播放 ▶',
  acts: '幕',
  lines: '句',
  startHint: '點擊畫面 / 空白鍵推進',
  act: '第{n}幕',
  chapters: '章節選單',
  chaptersTitle: '選擇章節播放',
  kaisetsu: '解說',
  auto: '自動',
  autoFast: '倍速',
  prev: '← 上一句',
  restart: '重新開始',
  exit: '結束',
  me: '我',
  innerName: '內心の声',
  noteTitle: '為什麼這個回答好',
  nextHint: '▼ 下一句',
  nextAnswer: '看回答 ▶',
  nextReport: '看評價 ▶',
  shadowHint: '🎤 先開口說出你的答案，再看示範',
  menu: '選單',
  voice: '語音',
  packSection: '各公司面試包',
  staticSection: '台本',
  packBuilding: '語音生成中…（僅首次，約 1 分鐘）',
  packAudioNone: '語音未生成',
  packAudioPartial: '語音部分已生成',
  packLoadFailed: '台本載入失敗',
  archive: '封存',
  archivedSection: '已封存',
  restore: '還原',
  favorLabel: '面試官',
  reportTitle: '面試評價報告',
  reportBy: '評價者',
  finalFavor: '最終評價',
  overall: '總評',
  replay: '再看一次',
  backToTitle: '回到腳本選單',
  close: '關閉',
  reviewMode: '復習模式',
  reviewTitle: '面試劇場 總複習',
  reviewSub: '一次展開所有台本，捲動就能整體回顧。',
  reviewToc: '目錄',
  reviewSearch: '搜尋',
  reviewBookmarked: '已收藏',
  reviewShowInner: '心裡話',
  reviewModeFull: '全文',
  reviewModeMine: '只看我的回答',
  reviewKpiViews: '瀏覽次數',
  reviewKpiToday: '今天複習時間',
  reviewPickTitle: '選擇要復習的劇本',
};

export type VNUIDict = typeof ja;

export const VN_UI: Record<VNLang, VNUIDict> = { ja, zh };
